import {nanoid} from 'nanoid'

export const books = [
    {
        id:nanoid(),
        title:"Big Magic",
        ratings:4.0,
        img:"https://m.media-amazon.com/images/I/51fqxtaYzML._SX308_BO1,204,203,200_.jpg",
        genre:"Motivational",
        tags:["Creative","Better Living"],
        reviews:["Smart but unpretentious, funny, warm, and generous … By the end of one of her books, you feel as if she is your friend, too ― San Francisco Chronicle", "Smart but unpretentious, funny, warm, and generous … By the end of one of her books, you feel as if she is your friend, too ― San Francisco Chronicle"],
        publisher:"Bloomsbury Publishing PLC",
        author:"Elizabeth Gilbert",
        aboutAuthor:"Elizabeth Gilbert is the Number One New York Times bestselling author of Eat Pray Love and several other internationally bestselling books of fiction and non-fiction. Her story collection Pilgrims was a finalist for the PEN/Hemingway award; The Last American Man was a finalist for both the National Book Award and the National Book Critics Circle Award. Her follow-up memoir to Eat Pray Love, Committed, became an instant Number One New York Times bestseller. She has published two novels, Stern Men and The Signature of All Things, which was longlisted for the Baileys Women's Prize for Fiction and shortlisted for the Wellcome Book Prize. She lives in New Jersey. www.elizabethgilbert.com @GilbertLiz",
        releasedYear:2016,
        releasedDate:"21 January 2016",
        description:"Readers of all ages and walks of life have drawn inspiration from Elizabeth Gilbert’s books for years. Now, this beloved author shares her wisdom and unique understanding of creativity, shattering the perceptions of mystery and suffering that surround the process – and showing us all just how easy it can be. By sharing stories from her own life, as well as those from her friends and the people that have inspired her, Elizabeth Gilbert challenges us to embrace our curiosity, tackle what we most love and face down what we most fear. Whether you long to write a book, create art, cope with challenges at work, embark on a long-held dream, or simply to make your everyday life more vivid and rewarding, Big Magic will take you on a journey of exploration filled with wonder and unexpected joys.",
        price:29.99,
        stock:20,
        followers:31,
        likes:15,
    },
    {
        
        id:nanoid(),
        title:"Effective Python",
        ratings:4.0,
        img:"https://m.media-amazon.com/images/I/81PsluXkpCL.jpg",
        genre:"Educational",
        tags:["Programming","Computer Engineering"],
        reviews:["It’s easy to start developing programs with Python, which is why the language is so popular. However, Python’s unique strengths, charms, and expressiveness can be hard to grasp, and there are hidden pitfalls that can easily trip you up. - Larry Conaway, Byte Systems USA"],
        publisher:"Addison-Wesley Inc USA",
        author:"Brett Slatkin",
        aboutAuthor:"Brett Slatkin is a principal software engineer at Google. He is the technical co-founder of Google Surveys, the co-creator of the PubSubHubbub protocol, and he launched Google’s first cloud computing product (App Engine). Fourteen years ago, he cut his teeth using Python to manage Google’s enormous fleet of servers. Outside of his day job, he likes to play piano and surf (both poorly). He also enjoys writing about programming-related topics on his personal website (https://onebigfluke.com). He earned his B.S. in computer engineering from Columbia University in the City of New York. He lives in San Francisco.",
        releasedYear:2016,
        releasedDate:"17 January 2020",
        description:"Updated and Expanded for Python 3 It’s easy to start developing programs with Python, which is why the language is so popular. However, Python’s unique strengths, charms, and expressiveness can be hard to grasp, and there are hidden pitfalls that can easily trip you up. This second edition of Effective Python will help you master a truly “Pythonic” approach to programming, harnessing Python’s full power to write exceptionally robust and well-performing code. Using the concise, scenario-driven style pioneered in Scott Meyers’ best-selling Effective C++, Brett Slatkin brings together 90 Python best practices, tips, and shortcuts, and explains them with realistic code examples so that you can embrace Python with confidence. Drawing on years of experience building Python infrastructure at Google, Slatkin uncovers little-known quirks and idioms that powerfully impact code behavior and performance. You’ll understand the best way to accomplish key tasks so you can write code that’s easier to understand, maintain, and improve.",
        price:32.50,
        stock:10,
        followers:400,
        likes:35,
    },

    {
        
        id:nanoid(),
        title:"Built to Last",
        ratings:4.0,
        img:"https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/O/S/124210_1544270025.jpg",
        genre:"Business",
        tags:["Entreprenuership", "Career Growth", "Finance"],
        reviews:["I read this book years ago but never got around to reviewing it. I've recently read it two more times in the last year. It is that good. I see it as an essential book for start-up entrepreneurs because it is packed with important truths. -Paul Simister, United Kingdom"],
        publisher:"Collins Business Corp. USA",
        author:"Jim Collins",
        aboutAuthor:"Jim Collins is a student and teacher of enduring great companies -- how they grow, how they attain superior performance, and how good companies can become great companies.Having invested over a decade of research into the topic, Jim has co-authored three books, including the classic Built to Last, a fixture on the Business Week bestseller list for more than five years, generating over 70 printings and translations into 16 languages.His work has been featured in Fortune, The Economist, Business Week, USA Today, Industry Week, Inc., Harvard Business Review and Fast Company. Driven by a relentless curiosity, Jim began his research and teaching career on the faculty at Stanford Graduate School of Business, where he received the Distinguished Teaching Award in 1992.In 1995, he founded a management laboratory in Boulder, Colorado, where he now conducts multi-year research projects and works with executives from the private, public, and social sectors.",
        releasedYear:2002,
        releasedDate:"September 1, 2002",
        description:"Drawing upon a six-year research project at the Stanford University Graduate School of Business, James C. Collins and Jerry I. Porras took eighteen truly exceptional and long-lasting companies and studied each in direct comparison to one of its top competitors. They examined the companies from their very beginnings to the present day -- as start-ups, as midsize companies, and as large corporations. Throughout, the authors asked: 'What makes the truly exceptional companies different from the comparison companies and what were the common practices these enduringly great companies followed throughout their history?' Filled with hundreds of specific examples and organized into a coherent framework of practical concepts that can be applied by managers and entrepreneurs at all levels, Built to Last provides a master blueprint for building organizations that will prosper long into the 21st century and beyond.",
        price:15.94,
        stock:0,
        followers:104,
        likes:50,
    },

    {
        
        id:nanoid(),
        title:"The Lean Startup",
        ratings:3,
        img:"https://m.media-amazon.com/images/I/51PAIR77wJL.jpg",
        genre:"Business",
        tags:["Business Management","Finance"],
        reviews:["Using an effective process to create a high value company has never been so important in these rapid changing times. The Lean Startup methodology explores this effective process that is going to save lots of wasted time and energy that could be used to further innovate and deliver even greater value to our lovely customers.- Ed Chang, CEO Eagle Venture Capital"],
        publisher:"Randon House Publishing",
        author:"Eric Ries",
        aboutAuthor:"Eric Ries is an entrepreneur and author of the New York Times bestseller The Lean Startup: How Today's Entrepreneurs Use Continuous Innovation to Create Radically Successful Business, published by Crown Business.He serves on the advisory board of a number of technology startups, and has consulted to new and established companies as well as venture capital firms. In 2010, he was named entrepreneur-in-residence at Harvard Business School and is currently an IDEO Fellow. Previously he co-founded and served as CTO of IMVU, his third startup. In 2007, BusinessWeek named him one of the Best Young Entrepreneurs of Tech. In 2009, he was honored with a TechFellow award in the category of Engineering Leadership.The Lean Startup methodology has been written about in The New York Times, The Wall Street Journal, Harvard Business Review,Inc. (where he appeared on the cover), Wired, Fast Company, and countless blogs. He lives in San Francisco.",
        releasedYear:2011,
        releasedDate:"September 13, 2011",
        description:"Most startups fail. But many of those failures are preventable. The Lean Startup is a new approach being adopted across the globe, changing the way companies are built and new products are launched.Eric Ries defines a startup as an organization dedicated to creating something new under conditions of extreme uncertainty. This is just as true for one person in a garage or a group of seasoned professionals in a Fortune 500 boardroom. What they have in common is a mission to penetrate that fog of uncertainty to discover a successful path to a sustainable business.",
        price:16.99,
        stock:5,
        followers:40,
        likes:25,
    },

    {
        
        id:nanoid(),
        title:"The Effective Engineer",
        ratings:5.0,
        img:"https://m.media-amazon.com/images/I/61AdWLqiIBL.jpg",
        genre:"Software Engineering",
        tags:["Engineering","Programming","Software Design"],
        reviews:["I hope more people embrace Edmond's philosophy and techniques to make their companies and careers more successful.- Bret Taylor, CEO of Quip & Former CTO of Facebook","I wish I had this manual to give my engineers when I was a VP of Engineering at Twitter. This summarizes and presents everything I used to tell my team.- Raffi Krikorian, Former Engineering VP at Twitter"],
        publisher:"Effective Bookshelf Inc. USA",
        author:"Edmond Lau",
        aboutAuthor:"For the past decade, Edmond Lau has worked as a software engineer in some of the top technology companies in Silicon Valley, including Google, Ooyala, Quora, and Quip. He's passionate about building great engineering teams. He's interviewed over 500+ engineering candidates throughout his career as well as spoken to teams across the country on how to build great engineering cultures. At Quora, he built out the onboarding and mentoring programs used to train dozens of new engineering hires and helped grow the team from 12 to over 70. His engineering and career advice has been featured on Forbes, Time, Slate, Inc., and Fortune. He's also guest lectured at both MIT and Stanford on software design. He holds a Bachelor's and Master's in Computer Science from MIT.",
        releasedYear:2015,
        releasedDate:"March 19, 2015",
        description:"",
        price:35.17,
        stock:0,
        followers:120,
        likes:65,
    },

]